import type { EntregaCatalogo } from '@/lib/entregas/tipos'

/**
 * Fila deste portal. Cada item é um passo do Heladri (planilha do SESC).
 * A camada de operação é genérica; o catálogo abaixo é só deste produto.
 */
export const CATALOGO_ENTREGAS: EntregaCatalogo[] = [
  {
    id: 'av1-operacao',
    nome: 'Operação da aplicação',
    resumo:
      'Usuários, versão, implantações, esteira, logs e saúde do ambiente. Vale para operar o portal; o trabalho continua sendo a planilha do SESC.',
    tipo: 'nova_funcionalidade',
    versaoPrevista: '0.1.0',
    versaoEfetiva: '0.1.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 0,
    dependsOn: [],
    areas: ['ui', 'auth', 'saude', 'docs'],
  },
  {
    id: 'projeto-planilha',
    nome: 'Projeto a partir da planilha do SESC',
    resumo:
      'Depois do login, a lista de projetos. Criar novo projeto pede nome, data e o upload da planilha. A tela de preenchimento nasce desse arquivo, na máquina.',
    tipo: 'nova_funcionalidade',
    versaoPrevista: '0.2.0',
    versaoEfetiva: '0.2.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 10,
    dependsOn: ['av1-operacao'],
    areas: ['planilha', 'ui'],
    major: true,
  },
  {
    id: 'contas-manuais',
    nome: 'Contas criadas pelo administrador',
    resumo:
      'O administrador cria a conta com usuário e senha, troca a senha e exclui o usuário. O pedido de acesso continua na fila; o e-mail de confirmação fica na entrega do remetente.',
    tipo: 'nova_funcionalidade',
    versaoPrevista: '0.3.0',
    versaoEfetiva: '0.3.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 15,
    dependsOn: ['av1-operacao'],
    areas: ['auth', 'ui'],
  },
  {
    id: 'capitulos-planilha',
    nome: 'Preenchimento por capítulos',
    resumo:
      'O índice à esquerda lista as seções da planilha. Capítulo preenchido fica verde; o que falta valor fica laranja. Baixar devolve o mesmo arquivo, com os valores gravados nas células de entrada.',
    tipo: 'nova_funcionalidade',
    versaoPrevista: '0.4.0',
    versaoEfetiva: '0.4.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 18,
    dependsOn: ['projeto-planilha'],
    areas: ['planilha', 'ui'],
  },
  {
    id: 'preenchimento',
    nome: 'Rascunho, arquivo referencial e conclusão',
    resumo:
      'A planilha enviada fica amarrada ao projeto. O banco guarda os dados do preenchimento. Dá para salvar em rascunho. Concluir grava esses valores numa cópia fiel da planilha.',
    tipo: 'nova_funcionalidade',
    versaoPrevista: '0.5.0',
    versaoEfetiva: '0.5.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 20,
    dependsOn: ['projeto-planilha'],
    areas: ['planilha', 'ui'],
  },
  {
    id: 'extra-servico',
    nome: 'Extra no item de serviço',
    resumo:
      'No serviço, um extra opcional compõe o preço na tela, em reais, percentual ou os dois, sempre sobre o valor base. A planilha exportada grava só o valor final, sem o cálculo.',
    tipo: 'nova_funcionalidade',
    versaoPrevista: '0.6.0',
    versaoEfetiva: '0.6.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 25,
    dependsOn: ['preenchimento'],
    areas: ['planilha', 'ui'],
  },
  {
    id: 'planilha-cotacao',
    nome: 'Preenchimento da planilha de cotação',
    resumo:
      'A planilha de cotação deste trabalho abre por capítulos, com valor, observação e extra de serviço. Concluir devolve o mesmo arquivo. Não rateia esses números para as colunas F e G da planilha do SESC.',
    tipo: 'nova_funcionalidade',
    versaoPrevista: '0.6.0',
    versaoEfetiva: '0.6.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 28,
    dependsOn: ['preenchimento'],
    areas: ['planilha', 'ui'],
  },
  {
    id: 'git-proprio',
    nome: 'Repositório Git só do Heladri',
    resumo:
      'O portal está no remoto heladriapp-spec/app. A publicação lê esse Git. Não travou o corte da planilha.',
    tipo: 'melhoria',
    versaoPrevista: '0.7.0',
    versaoEfetiva: '0.6.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 30,
    dependsOn: ['av1-operacao'],
    areas: ['docs'],
  },
  {
    id: 'supabase',
    nome: 'Supabase: banco, arquivos e sessão na nuvem',
    resumo:
      'Com a chave configurada, usuários, pedidos, projetos e as planilhas ficam no Postgres e no Storage. Sem a chave, a mesma operação usa a pasta local. A chave fica fora do Git. O arquivo não entra numa tabela.',
    tipo: 'nova_funcionalidade',
    versaoPrevista: '0.8.0',
    versaoEfetiva: '0.6.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 40,
    dependsOn: ['git-proprio'],
    areas: ['banco', 'auth'],
  },
  {
    id: 'email',
    nome: 'Remetente de confirmação e de senha',
    resumo:
      'Aprovar um pedido envia o link de uso único para confirmar o acesso e definir usuário e senha. Esqueci a senha usa o mesmo remetente. Contas da instalação continuam sem e-mail.',
    tipo: 'melhoria',
    versaoPrevista: '0.9.0',
    versaoEfetiva: '0.7.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 50,
    dependsOn: ['supabase'],
    areas: ['auth'],
  },
  {
    id: 'vercel',
    nome: 'Publicação na Vercel a partir do Git',
    resumo:
      'A aplicação no ar sai do Git, no plano gratuito, sem banco da Vercel. A planilha não usa armazenamento da Vercel.',
    tipo: 'melhoria',
    versaoPrevista: '0.10.0',
    versaoEfetiva: '0.6.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 60,
    dependsOn: ['git-proprio', 'supabase'],
    areas: ['docs'],
  },
  {
    id: 'boas-vindas',
    nome: 'Boas-vindas com o nome de quem entrou',
    resumo:
      'Depois do login, um recado curto com o nome da conta: deixa a planilha manual e preenche o trabalho aqui. Fecha em cinco segundos ou em Fechar. Não mostrar de novo fica na conta.',
    tipo: 'nova_funcionalidade',
    versaoPrevista: '0.11.0',
    versaoEfetiva: '0.8.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 62,
    dependsOn: ['av1-operacao'],
    areas: ['ui', 'auth'],
  },
  {
    id: 'feedback-acao',
    nome: 'Aviso de processamento e de ação concluída',
    resumo:
      'Todo botão que dispara uma ação mostra Processando, com um relógio, e depois Ação concluída. Vale para cadastro, exclusão e o restante.',
    tipo: 'nova_funcionalidade',
    versaoPrevista: '0.12.0',
    versaoEfetiva: '0.8.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 64,
    dependsOn: ['av1-operacao'],
    areas: ['ui'],
  },
  {
    id: 'sair-atalho',
    nome: 'Sair com Alt+Esc',
    resumo:
      'Alt+Esc encerra a sessão em qualquer tela autenticada. O aviso diz Encerrando sessão e, ao terminar, Sessão encerrada. O botão Sair usa o mesmo aviso.',
    tipo: 'nova_funcionalidade',
    versaoPrevista: '0.13.0',
    versaoEfetiva: '0.8.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 66,
    dependsOn: ['av1-operacao'],
    areas: ['ui', 'auth'],
  },
  {
    id: 'interface-leve',
    nome: 'Modernidade da interface',
    resumo:
      'A tela fica mais moderna e mais leve, com o jeito de um aplicativo. Onde o gesto já é claro, o ícone acompanha a ação: navegar, criar, salvar, baixar, sair e o estado do capítulo. O texto fica quando a pessoa precisa ler.',
    tipo: 'melhoria',
    versaoPrevista: '0.14.0',
    versaoEfetiva: '0.9.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 67,
    dependsOn: ['av1-operacao'],
    areas: ['ui'],
  },
  {
    id: 'interacao-leve',
    nome: 'Modernidade nas ações',
    resumo:
      'A interação fica moderna e leve. O botão clicado mostra o que está acontecendo: carregando o documento, salvando, gerando o arquivo. Ao terminar, a frase diz o que deu certo, como documento salvo. Não pergunta se deseja salvar. O efeito fica no controle, sem cobrir a tela.',
    tipo: 'melhoria',
    versaoPrevista: '0.15.0',
    versaoEfetiva: '0.11.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 68,
    dependsOn: ['feedback-acao'],
    areas: ['ui'],
  },
  {
    id: 'erro-inesperado',
    nome: 'Erro inesperado para quem usa',
    resumo:
      'Falha que a tela não previu aparece como Erro inesperado. Consulte o administrador. O detalhe técnico fica de fora. Senha incorreta e as outras recusas previstas continuam com o texto delas.',
    tipo: 'correcao',
    versaoPrevista: '0.16.0',
    versaoEfetiva: '0.10.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 69,
    dependsOn: ['av1-operacao'],
    areas: ['ui'],
  },
  {
    id: 'workflow-autor',
    nome: 'Workflow: o autor prepara e envia',
    resumo:
      'Preparação, execução e concluído substituem os quatro status atuais. Projeto antigo sem arquivo continua abrindo. Projeto novo só nasce com a planilha lida. Salvar não muda a etapa. O autor envia para execução e acompanha sem receber os valores nem o arquivo. Baixar o resultado e alterar um concluído são recusados no servidor. A conta ganha a marca de executor, desligada.',
    tipo: 'nova_funcionalidade',
    versaoPrevista: '0.12.0',
    versaoEfetiva: '0.12.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 70,
    dependsOn: ['preenchimento'],
    areas: ['banco', 'planilha', 'ui', 'auth'],
    major: true,
  },
  {
    id: 'workflow-executor',
    nome: 'Workflow: assumir, concluir e baixar',
    resumo:
      'Quem tem a marca de executor vê a fila e assume um projeto. Só o responsável edita e conclui. O autor vê o resultado e baixa o arquivo final. Antes de concluído, o download é recusado.',
    tipo: 'nova_funcionalidade',
    versaoPrevista: '0.13.0',
    versaoEfetiva: '1.1.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 71,
    dependsOn: ['workflow-autor'],
    areas: ['planilha', 'ui', 'auth'],
    major: true,
  },
  {
    id: 'workflow-retorno',
    nome: 'Workflow: prévia, devolução e histórico',
    resumo:
      'O responsável libera ou recolhe a prévia. O autor lê os valores e não baixa. Devolver volta para preparação, pede motivo e tira o responsável. O histórico lista quem enviou, assumiu, devolveu e concluiu, sem cópia do formulário.',
    tipo: 'nova_funcionalidade',
    versaoPrevista: '0.14.0',
    versaoEfetiva: null,
    statusBase: 'planejado',
    implantado: false,
    ordemPrioridade: 72,
    dependsOn: ['workflow-executor'],
    areas: ['planilha', 'ui'],
  },
  {
    id: 'versoes-planilha',
    nome: 'Histórico e versões do preenchimento',
    resumo:
      'Salvar registra quem alterou cada campo. Excluir e reincluir linha fica no histórico. A lista de versões mostra o que mudou, sem guardar o arquivo. O administrador restaura uma versão e inclui ou remove participante.',
    tipo: 'nova_funcionalidade',
    versaoPrevista: '1.0.0',
    versaoEfetiva: '1.0.0',
    statusBase: 'nesta_versao',
    implantado: true,
    ordemPrioridade: 80,
    dependsOn: ['preenchimento'],
    areas: ['planilha', 'banco'],
  },
  {
    id: 'segundo-arquivo',
    nome: 'Segundo trabalho antes de generalizar o leitor',
    resumo:
      'Outra planilha do SESC, para ver se aba, colunas e fórmulas se repetem. Até lá o Anexo III do Cosmo/Chão não vira modelo universal.',
    tipo: 'melhoria',
    versaoPrevista: '1.1.0',
    versaoEfetiva: null,
    statusBase: 'planejado',
    implantado: false,
    ordemPrioridade: 85,
    dependsOn: ['projeto-planilha'],
    areas: ['planilha', 'docs'],
  },
  {
    id: 'motor-cotacao',
    nome: 'Motor de cotação deste trabalho',
    resumo:
      'Rateio automático de material e mão de obra para as colunas F e G da planilha do SESC. Saiu deste corte: a cotação é preenchida no próprio arquivo.',
    tipo: 'nova_funcionalidade',
    versaoPrevista: '1.2.0',
    versaoEfetiva: null,
    statusBase: 'fora_de_escopo',
    implantado: false,
    ordemPrioridade: 100,
    dependsOn: ['preenchimento'],
    areas: ['planilha'],
    major: true,
  },
]

export function entregaPorId(id: string) {
  return CATALOGO_ENTREGAS.find((item) => item.id === id) ?? null
}

export const AREAS_CRITICAS: Array<EntregaCatalogo['areas'][number]> = [
  'banco',
  'auth',
  'planilha',
]
